"""add articles_hashtags associate table

Revision ID: da8e754b52af
Revises: 09350d5136e1
Create Date: 2023-03-22 20:08:42.366666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8e754b52af'
down_revision = '09350d5136e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_hashtags',
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('hashtag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles_hashtags')
    # ### end Alembic commands ###
